### PR TITLE
Give multiple instances separate log files

### LINKED ISSUE #40: Unable to have more than one instance open
If an instance of hUGETracker is already open, trying to open another one does nothing. This seems to be because of output.log, the first instance locks the file and the second instance is unable to open it. Though nothing is ever logged to output, is it even used at all?

### PR DESCRIPTION
**Pull request by QuinnPainter**
fixes #40

### CODE REVIEW

**Comment by SuperDisk** [comment]
Cool, thank you for this. As I understand it, this basically allows for five concurrent instances before running into the same problem in issue #40 right?

**Comment by QuinnPainter** [comment]
It'll allow five log files, then further instances will just not log info anywhere instead of crashing like before.

**Comment by SuperDisk** [comment]
I really appreciate this PR, but I think a better idea might be to just not write to a log file if it can't `Assign` output.log. I think this would involve catching an exception like you're doing and then replacing `Output` with a dummy instance that ignores output somehow.

**Comment by QuinnPainter** [comment]
You're right, I didn't notice that by not assigning output to anything that attempts to write to it will crash the program. We'll need to find some way to redirect output somewhere else. I can also replace the 5 log files with just 1 for the first instance of the program, if you think that's better.
I'm not sure that this log file as working at all though. All of the output logs are using StdErr, but to be going into this file they should be using Output, right? StdErr isn't going into the file at all.

**Comment by QuinnPainter** [comment]
oops, didn't realise pushing that would add it to this pull request

**Pull request closed without merging**
