### PR TITLE
Load font again on Linux and BSDs

### PR DESCRIPTION
**Pull request by ISSOtm**
Fix typoed conditional introduced in 357b083666442cb2760c9be6c8544e5abae5c8c0

### CODE REVIEW

**Comment by ISSOtm** [comment]
Crap, macOS fails because I guess it's considered a BSD?

**Comment by SuperDisk** [comment]
I could have sworn I fixed this... oh well. Maybe lost accidentally in a `git checkout -- .` or something. I think for now it would be better to check explicitly for (I guess) `LINUX`, `FREEBSD` and `OPENBSD` rather than just `BSD` in general, since annoyingly (but correctly) MacOS is considered a BSD.

**Comment by SuperDisk** [comment]
Closing here as this should be addressed in 9af31a8. Thanks!

**Comment by ISSOtm** [comment]
I guess that depends on whether NetBSD users use FontConfig? Alternatively, instead of guessing based on OS, you *could* weakly reference the FontConfig symbols on all BSDs, and skip the calls if the symbols wind up being NULL.

**Pull request closed without merging**
